name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your proposal.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like to see.
      placeholder: I'd like dream_test to support...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API (if applicable)
      description: Show what the API might look like if you have an idea.
      placeholder: |
        ```gleam
        import dream_test/unit.{describe, it}

        pub fn example() {
          describe("Example", [
            // Your proposed API
          ])
        }
        ```
      render: gleam

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What alternatives have you considered? Why is your proposal better?
      placeholder: I considered using... but it doesn't work because...

  - type: textarea
    id: philosophy
    attributes:
      label: Fits dream_test's philosophy?
      description: |
        How does this fit with dream_test's philosophy of clean, pipe-friendly assertions without magic?
      placeholder: This fits dream_test's philosophy because...
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Would this be a breaking change?
      description: Would existing code need to be modified?
      options:
        - "No, fully backward compatible"
        - "Yes, existing code would break"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Current workaround
      description: How are you currently working around this limitation (if applicable)?
      placeholder: Currently I'm doing... but it's not ideal because...

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, examples, or screenshots about the feature request.
      placeholder: Any other relevant information...











